### ISSUE TITLE
スニペットを検知したらシェル芸実行して欲しい

### ISSUE THREAD

**Issue by mtbr-msys** [nkc-ug/NKCUG_Slack_Bot#21]

**Comment by huequica** [comment]
![Screen Shot 2019-12-23 at 4 09 21](https://user-images.githubusercontent.com/40014236/71326146-2ce8b300-253a-11ea-87d3-c1dbbc2587d2.png)
それなりに出来たので、もう少し仕様通り(リプライ+特定書式付きのみにするとか)にしたら提出します
